CharacterNotesDB = {
	["profiles"] = {
		["Default"] = {
		},
	},
	["profileKeys"] = {
		["Ryadread - Wild Growth"] = "Default",
		["Karmentary - Wild Growth"] = "Default",
		["Ryabank - Dreamscythe"] = "Default",
		["Mackstabby - Wild Growth"] = "Default",
		["Bankofkarz - Wild Growth"] = "Default",
		["Karzik - Wild Growth"] = "Default",
		["Karnock - Lone Wolf"] = "Default",
		["Zanex - Wild Growth"] = "Default",
		["Goldaholic - Lone Wolf"] = "Default",
		["Karzik - Lone Wolf"] = "Default",
		["Karz - Westfall"] = "Default",
		["Kar - Dreamscythe"] = "Default",
		["Karshot - Wild Growth"] = "Default",
		["Karzik - Dreamscythe"] = "Default",
		["Ryadread - Lone Wolf"] = "Default",
		["Sereus - Dreamscythe"] = "Default",
		["Karzbank - Lone Wolf"] = "Default",
		["Karzod - Lone Wolf"] = "Default",
		["Karzod - Wild Growth"] = "Default",
	},
	["realm"] = {
		["Westfall"] = {
			["removedSpacesFromRealm"] = true,
		},
		["Lone Wolf"] = {
			["notes"] = {
				["Tullana"] = "Helped w/ quest in Durotar.",
				["Artmagar"] = "Helped me in Silverpine Forest.",
				["Dinkin"] = "Helped me get a Rune in Mulgore.",
				["Zerotozed"] = "Skinned one of my kills before I could skin it.",
			},
			["ratings"] = {
				["Tullana"] = 1,
				["Artmagar"] = 1,
				["Dinkin"] = 1,
				["Zerotozed"] = -1,
			},
			["removedSpacesFromRealm"] = true,
		},
		["Wild Growth"] = {
			["notes"] = {
				["Sparrowmoo"] = "Ganked escort quest on my whole group.",
				["Hellgash"] = "Helped w/ Sniper Rune quest.",
			},
			["ratings"] = {
				["Sparrowmoo"] = -1,
				["Hellgash"] = 1,
			},
			["removedSpacesFromRealm"] = true,
		},
		["Dreamscythe"] = {
			["notes"] = {
				["Hitmann"] = "Wanted to reserve everything from Mara.",
				["Aggravator"] = "Spellcleave SM",
				["Stinkydiver"] = "Ganked quest from me in Dustwallow.",
				["Slampiece"] = "Ganked a chest on us.",
				["Yrithzd"] = "Grouped in Westfall",
				["Shmerkele"] = "Horrible Tank",
				["Yurithzd"] = "Grouped in Westfall",
				["Mirenth"] = "Grouped in Westfall.",
				["Giantsbane"] = "Ganked a chest on us.",
				["Pyramids"] = "Spellcleave SM",
				["Sonaden"] = "Satchel quest in Desolace.",
				["Parakeet"] = "Helped w/ trying to get the Riddle quest.",
				["Chadduck"] = "Helped us get our ZF Mallet.",
				["Diabeatus"] = "Grouped with in Southshore.",
				["Slj"] = "Grouped w/ Dark Council Quest",
				["Anddie"] = "Gave me turtle meat.",
			},
			["ratings"] = {
				["Hitmann"] = -1,
				["Aggravator"] = 1,
				["Slampiece"] = -1,
				["Stinkydiver"] = -1,
				["Pyramids"] = 1,
				["Yurithzd"] = 1,
				["Slj"] = 1,
				["Giantsbane"] = -1,
				["Shmerkele"] = -1,
				["Sonaden"] = 1,
				["Parakeet"] = 1,
				["Chadduck"] = 1,
				["Diabeatus"] = 1,
				["Mirenth"] = 1,
				["Anddie"] = 1,
			},
			["removedSpacesFromRealm"] = true,
		},
	},
}
